Switch to streaming parsing and IO
Updated Changelog

Disabled GHC HEAD build.

GHC is encountering an interface file problem on travis. Not my circus,
not my monkey.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,41 +1,50 @@
-env:
-#  - CABALVER=1.18 GHCVER=7.8.3
-  - CABALVER=1.22 GHCVER=7.10.1
+language: c
+
+# explicitly request container-based infrastructure
+sudo: false
+
+cache:
+  directories:
+  - tests/mcpp-2.7.2
+
+matrix:
+  include:
+    - env: CABALVER=1.22 GHCVER=7.10.1
+      addons:
+        apt:
+          packages:
+          - cabal-install-1.22
+          - ghc-7.10.1
+          - libc6-dev-i386
+          sources: hvr-ghc
+
+    # - env: CABALVER=head GHCVER=head
+    #   addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
+
+  allow_failures:
+   - env: CABALVER=head GHCVER=head
 
 before_install:
-  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-  - travis_retry sudo apt-get update
-  - travis_retry sudo apt-get -qq -y install cabal-install-$CABALVER ghc-$GHCVER-prof build-essential gcc-multilib libc6-dev
-  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 
 install:
-  - cabal --version
-  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-  - travis_retry cabal update
-  - |
-    if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ]  || [ ${GHCVER%.*} = "7.10" ]; then
-      travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
-      export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
-    else
-      travis_retry sudo apt-get install happy alex
-    fi
-  
-  - cabal install --dependencies-only --enable-tests
-  - (cd tests && curl http://tcpdiag.dl.sourceforge.net/project/mcpp/mcpp/V.2.7.2/mcpp-2.7.2.tar.gz > mcpp-2.7.2.tar.gz && tar xf mcpp-2.7.2.tar.gz)
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry cabal update
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
+ - (cd tests && curl http://tcpdiag.dl.sourceforge.net/project/mcpp/mcpp/V.2.7.2/mcpp-2.7.2.tar.gz > mcpp-2.7.2.tar.gz && tar xf mcpp-2.7.2.tar.gz)
 
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
 script:
-  - cabal configure --enable-tests
-  - cabal build
-  - (cd tests && ./mcpp-validation.sh)
-  - cabal check || true
-  - cabal sdist
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - (cd tests && ./mcpp-validation.sh)
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
 
-# The following scriptlet checks that the resulting source distribution can be built & installed
-  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
-    cd dist/;
-    if [ -f "$SRC_TGZ" ]; then
-       cabal install --force-reinstalls "$SRC_TGZ";
-    else
-       echo "expected '$SRC_TGZ' not found";
-       exit 1;
-    fi
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
